#+title: Tieminos



* Introduction
My current music workshop, all my clojure code-music creation since mid-2021 lives here.

Mainly uses ~Supercollider~ via ~Overtone~, my microtonality library [[https://github.com/diegovdc/erv][erv]] and my sequencing library [[https://github.com/diegovdc/time-tiem][time-tiem]].

* MIDI
** MIDI controller template
#+begin_src clojure
(require '[tieminos.midi.core :refer [midi-in-event get-oxygen!]])
(midi-in-event
  :midi-input (get-oxygen!)
  :note-on (fn [{:keys [note channel velocity] :as data}]
             (println data)
             (println (keys data)))
  :note-off (fn [{:keys [note channel]}]
              (println :note-off)))

#+end_src
** MPE Controller (Exquis)
#+begin_src clojure
(require '[tieminos.midi.core :refer [midi-in-event get-exquis! exquis-cc clear-all-synths!]])

(require
  '[overtone.core :as o]
  '[tieminos.overtone-extensions :as oe]
  '[erv.utils.conversions :as conv]
  '[tieminos.math.utils :refer [linlin* linexp*]]
  '[tieminos.synths :refer [demo-sine]])

  (midi-in-event
   :midi-input (get-exquis!)
   :note-on (fn [{:keys [note velocity]}]
              (demo-sine :freq (conv/midi->cps
                                 ;; `exquis-cc` will get the current cc value from the exquis input state
                                (+ (exquis-cc 41) ;; Will produce a brief glissando on the attack
                                   note))
                         :amp (linlin* 0 127 0.4 0.9 velocity)))
   :keep-cc-state? {:log? true} ;; can be nil, true or {:log? boolean}. Logging will post cc changes to the repl. If MPE is used cc 74 (y-axis) will not be logged nor kept in the state
   :cc (fn [{:keys [note velocity]}]
          ;; for some reason javax.sound.midi misses some note-off messages so...
         (when (and (= note 21) ;; knob 1 click
                    (= velocity 127))
           (clear-all-synths!)))
   :before-gate-0 (fn [{:keys [velocity]} synth]
                    (o/ctl synth :r (linlin* 0 127 3 1 velocity)))
   :mpe {:x (fn [synth val]
              (let [note (::midi-note synth)]
                (o/ctl synth :freq (-> (linlin* 0 127 (- note 2) (+ note 2) val)
                                       (conv/midi->cps)))))
         :y (fn [synth val]
              (o/ctl synth :pan (linlin* 0 127 -1 1 val)))
         :z (fn [synth val]
              (o/ctl synth :amp (linexp* 0 127 0.1 1 val)))})
  
#+end_src

* Legato sustainer
Sustain a note or notes until they change. Useful within a loop (refrain) to prevent a note from being retriggered every time.
#+begin_src clojure
(require '[tieminos.overtone-extensions :as oe]
         '[tieminos.harmonic-experience.drones.sounds :refer [drone]]
         '[tieminos.harmonic-experience.sustainer :as legato])
  (def root 200)
  (legato/play! :id1 {:inst drone :params {:freq (* root 1)}})
  (legato/stop! :id1)
  (legato/multi :my-chord
         {1 {:inst drone :params {:freq (* root 1)}}
          3/2 {:inst drone :params {:freq (* root 3/2)}}})
  (legato/multi :my-chord {1 {:inst drone :params {:freq (* root 1)}}})
  (legato/multi :my-chord {1 {:inst drone :params {:freq (* root 2)}}})
  (legato/multi :my-chord {})
#+end_src

* Synthdefs
** Template Synth
=tieminos.sc-utils.synths.template-synth.v0= is an experimental feature that provides a way to generate variations of a synth based on user defined templates. It supports usage of vectors of variable sizes as args (e.g. for chords) as well as having =ugens= as arguments (e.g. for a passing in different filters to a synth).

#+begin_src clojure
(require '[overtone.core :as o]
         '[tieminos.sc-utils.synths.template-synth.v0 :refer [make-synth-fn
                                                              get-synth-variant
                                                              get-variant-data
                                                              modify-params2
                                                              describe-synth
                                                              variant-id]])

(make-synth-fn
  ;; synth (caller) name: a quoted symbol.
  ;; NOTE: This symbol will be defined in the namespace.
  'sawy
  ;; default args
  {:freq [500 900]
   :env-levels [0 1 0.1 1 0]
   :env-durs [1 3 1 2]
   :amp 1
   ;; template-able ugens, they are "passed in" dynamically to the synth (new synth versions are cached). They can access other arguments in the synth.
   :ugen/env '(o/env-gen (o/envelope env-levels env-durs) :action o/FREE)
   :ugen/fx1 '(o/distort)
   :ugen/mix '((fn [sig]
                 ;; if sig is a single sin-osc (not a vector) then don't call `o/mix`.
                 ;; NOTE: even if a single freq is passed in a vector, the sig will still come in not in a vector.
                 (if (vector? freq)
                   (o/mix sig)
                   sig)))
   ;; a default can be just a number
   :ugen/pan-pos 0}
  ;; ugen graph template: a quoted list containing a graph of ugens or keywords with the `ugen` namespace. They are subtituted by the passed in ugens. Otherwise the syntax is the same as the body of a `defsynth`.
  '(o/out 0
          (-> (o/sin-osc freq)
              :ugen/mix
              :ugen/fx1
              (o/pan2 :ugen/pan-pos)
              (o/free-verb)
              (* amp :ugen/env)))
  ;; remove all variations of the synth when `make-synth-fn` is called. `true` is the default value.
  {:reset? true})

;; This a synth can be called.
(sawy)

;; use a single freq (see the default `freq` param).
(sawy {:freq 200})

;; Pass a chord of a different size. NOTE: the `:ugen/mix` logic works with lists too
(sawy {:freq '(200 400 500)})

;; Of course env params can also be modified.
(sawy {:env-levels [0 1 0]
       :env-durs [0.001 1]})

;; remove the distortion
(sawy {:ugen/fx1 nil})

;; use a filter and increase the amp
(sawy {:amp 5
       ;; NOTE: using the double parenthesis syntax as the function is passed to a `->` macro. So except for the `'` the syntax is the same. 
       :ugen/fx1 '((fn [sig] (o/moog-ladder sig 900 0.2)))})

(sawy {:amp 5
       ;; As per the NOTE above we can use this syntax too.
       :ugen/fx1 '(o/moog-ladder 900 0.2)})

;; pass an ugen argument to another ugen
(sawy {:ugen/pan-pos '(o/lf-noise2 10)})

#+end_src

*** Advanced
**** Single synth variants and variant data

~get-variant-data~, ~get-synth-variant~, ~describe-synth~ and ~variant-id~.

#+begin_src clojure
;; NOTE: following the code block above.

;; Get all the relevant data related to a variant. 
(get-variant-data sawy {:ugen/pan-pos '(o/lf-noise2 10)})
(keys (get-variant-data sawy {:ugen/pan-pos '(o/lf-noise2 10)}))

;; Get a specific variant synth (an `Overtone` synth) given some sample params. NOTE: The namespace where the synth was defined should be provided.
(def sawy-pan-noise (get-synth-variant sawy {:ugen/pan-pos '(o/lf-noise2 10)}))

;; This is just an Overtone synth
(sawy-pan-noise :freq0 100
                :freq1 10000)

;; modify-params2 can be used if the params vector is too large.
(sawy-pan-noise (modify-params2 {:freq [100 300]}))

;; But of course the third frequency will never sound as the synth has not been generated to deal with that. In that case create another instance or use `sawy`.
(sawy-pan-noise (modify-params2 {:freq [100 300 10000]}))

;; The only difference is that the instance contains metadata describing it.
(meta sawy-pan-noise)

;; See the params and the ugen-form that is being used by this (`Overtone`) synth
(describe-synth sawy-pan-noise)


;; Get the id of a particular instance
(variant-id sawy {})
(variant-id sawy {:freq [100 300]})    ;; this should be the same instance, as the vector size because `:freq` is the same as the original
(variant-id sawy {:freq [100 300 500]}) ;; but this one is different
(variant-id sawy {:ugen/pan-pos '(o/lf-noise2 10)}) ;; and this one too

#+end_src
** Plugin syntax: =defplug=.
Notice that in the example above the =env-levels= and =env-durs= parameters are tied to =:ugen/env=. This makes it a problem for reusing these ugens contrary, to e.g. ~:ugen/fx1 '((fn [sig] (o/moog-ladder sig 900 0.2)))~ which is mostly autonomous. To facilitate the reuse of the =ugen= namespaced params. One can use =defplug=. 

#+begin_src clojure
(require '[overtone.core :as o]
         '[tieminos.sc-utils.synths.template-synth.v0 :refer [make-synth-fn defplug]])

(defplug env1
  ;; a map with the ugen params we want to access and their defaults
  {:env-levels [0 1 0.1 1 0]
   :env-durs [1 3 1 1]
   :ugen/env '(o/env-gen (o/envelope env-levels env-durs) :action o/FREE)})

(defplug env2
  {:attack 0.01
   :release 1
   :ugen/env '(o/env-gen (o/env-perc attack release) :action o/FREE)})

;; When a plugin expects an external param to be present (e.g. `freq`) then,
;; the 2-arity version takes as a first parameter a set of keys that should correspond to names of parameters.
;; Nevertheless they should be present on the synth. And it not they will fail.
(defplug freq-mixer
  #{:freq}
  {:ugen/freq-mixer  '((fn [sig]
                         ;; if sig is a single sin-osc (not a vector) then don't call `o/mix`.
                         ;; NOTE: even if a single freq is passed in a vector, the sig will still come in not in a vector.
                         (if (vector? freq)
                           (o/mix sig)
                           sig)))})

(make-synth-fn
  'siny
  (-> {:freq [500 900]
       :amp 1}
      (env1)
      (freq-mixer))
  '(o/out 0
          (-> (o/sin-osc freq)
              :ugen/freq-mixer 
              (o/pan2 0)
              (* amp :ugen/env)))
  {:reset? true})



(siny)

;; dynamically switch env1 for env2
(siny (-> {:freq 200} (env2)))

;; pass in a param for env2.
;; NOTE: it will not work if passed to the map that gets threaded in.
(siny (-> {:freq 200}
          (env2 {:attack 1})))
#+end_src


** Tips
When writting macros this ~ns~ gives access to the ugen operators
#+BEGIN_SRC clojure
[overtone.sc.ugen-collide-list :as oc]
#+END_SRC


* License

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.

